name: Build windows

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # TODO: Get host platform from somewher instead of specifying it explicitly here.
          - os: windows-latest
            bundle_os: windows
            ext: dll
            host: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      # - name: Install rust toolchain
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      #     override: true

      - name: Get npm cache dir
        id: npm-cache-dir
        shell: bash
        run: |
          echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node
          restore-keys: ${{ runner.os }}-node

      - run: .github/script/setup
        shell: bash

      - name: Install tree-sitter CLI
        run: npm install -g tree-sitter-cli

      - name: Determine version
        run: |
          echo BUNDLE_VERSION=$(script/bundle-version-prefix).${{ github.run_number }} >> $GITHUB_ENV
        shell: bash

      - run: script/compile all -target "${{ matrix.target }}" -version "${{ env.BUNDLE_VERSION  }}"
        shell: bash
        id: compile
        continue-on-error: ${{ runner.os != 'Windows' }}

      - run: script/inspect-binaries
        continue-on-error: true
        id: inspect-binary
        shell: bash

      - name: Rename cross-compilation's binary
        if: matrix.target
        run: |
          mv tree-sitter-grammars-${{ matrix.bundle_os }}-${{ env.BUNDLE_VERSION }}.tar.gz tree-sitter-grammars.${{ matrix.target }}.v${{ env.BUNDLE_VERSION }}.tar.gz
      - name: Make a target-explicit copy of native compilation's binary
        if: ${{ !matrix.target && matrix.host }}
        shell: bash
        run: |
          mv tree-sitter-grammars-${{ matrix.bundle_os }}-${{ env.BUNDLE_VERSION }}.tar.gz tree-sitter-grammars.${{ matrix.host }}.v${{ env.BUNDLE_VERSION }}.tar.gz

      - name: Upload binary
        if: steps.inspect-binary.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: tree-sitter-grammars
          path: tree-sitter-grammars*.tar.gz
          if-no-files-found: error

    outputs:
      version: ${{ env.BUNDLE_VERSION }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: tree-sitter-grammars
      - run: ls -R

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.build.outputs.version }}
          prerelease: true
          files: |
            tree-sitter-grammars*.tar.gz
